title: Meridian 59 Fan-made Wiki
description: Fan-made reference for Meridian 59 players

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
repo_url: 'https://github.com/meridian59db/meridian59db.github.io'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: false
hljs_style: github-gist
