title: Meridian 59 Fan-made Wiki
description: Meridian 59 Reference made by fans
remote_theme: meridian59db/meridian59db.github.io

# Theme settings:
repo_url: "https://github.com/meridian59db/meridian59db.github.io"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist
