name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build-api:
    runs-on: windows-latest
    steps:
      # Build
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Generate DBCs
        run: cmake -S dbd/cxx -B ../dbd && cmake --build ../dbd --target dbd2md_run --config RelWithDebInfo
      - name: Commit build files
        run: rm docs/dbc/.gitignore && git add . && git config user.name test && git config user.email test && git commit -m "bump"
      - name: Push to gh_pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: gh_pages