name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  build-api:
    runs-on: windows-latest
    steps:
      # Build
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Push to gh_pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: gh_pages
